# Site settings
title:       Yoocky's Blog
email:       me@yoocky.com
author:      Yoocky
description: "To the time to life, rather to life in time ."
baseurl:     ""
url:         "https://blog.yoocky.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons: false
github_username: yoocky
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     10
sass:
compressed: true
